### ISSUE TITLE
We need to test the branch coverage of some functions

### ISSUE THREAD

**Issue by btellstrom** [henrikglass/babel#1]
Below is listed the functions for which we test the branch coverage and the repsonsible collaborator.

@Pandington 
* [x] `read_mo`
* [x] `write_mo`

@henrikglass 
* [x] `unquote_string`
* [x] `tokenize`

@A1337li 
* [x] `format_timezone`
* [x] `match_skeleton`

@btellstrom 
* [x] `update`
* [x] `extract_javascript`

**Comment by btellstrom** [comment]
Branch coverage for `update` and `extract_script` has been determined by commit [90586e8](https://github.com/henrikglass/babel/commit/90586e863fb7e383dc0228de09aca9c37b553270 ).

Edit: Only for `update` due to a misunderstanding of the structure of tests

**Comment by ffsinger** [comment]
Branch coverage for `read_mo` and `write_mo` has been determined by commit 35ed411567f22cd2b88a94a9e4bff50abaf8c4bc

**Comment by btellstrom** [comment]
Now coverage has also been included for `extract_javascript` by commit [bed1252](https://github.com/henrikglass/babel/commit/bed1252ae8fd4138a9fb62476cea56dff9bb44d3)

**Comment by A1337li** [comment]
Branch coverage for `format_timezone` and `match_skeleton` has been included by commit 0c4f5c4

**Comment by ffsinger** [comment]
Everything has been merged into ASSIGNMENT3_DIY
